### ISSUE TITLE
可否发布一个windows平台编译好的 exe

### ISSUE THREAD

**Issue by poerlang** [generalzgd/flatbuffers-for-actionscript#1]
我尝试用vs2010编译,但是出现各种报错:

1>------ 已启动生成: 项目: flatsampletext, 配置: Debug x64 ------
2>------ 已启动生成: 项目: flatsamplebinary, 配置: Debug x64 ------
3>------ 已启动生成: 项目: flatc, 配置: Debug x64 ------
4>------ 已启动生成: 项目: flattests, 配置: Debug x64 ------
1>生成启动时间为 2016/9/19 10:40:22。
1>InitializeBuildStatus:
1>  正在对“flatsampletext.dir\Debug\flatsampletext.unsuccessfulbuild”执行 Touch 任务。
2>生成启动时间为 2016/9/19 10:40:22。
3>生成启动时间为 2016/9/19 10:40:22。
2>InitializeBuildStatus:
2>  正在对“flatsamplebinary.dir\Debug\flatsamplebinary.unsuccessfulbuild”执行 Touch 任务。
3>InitializeBuildStatus:
3>  正在对“flatc.dir\Debug\flatc.unsuccessfulbuild”执行 Touch 任务。
2>ClCompile:
2>  所有输出均为最新。
2>ManifestResourceCompile:
2>  所有输出均为最新。
1>ClCompile:
3>ClCompile:
3>  idl_gen_as.cpp
1>  idl_parser.cpp
2>LINK : fatal error LNK1123: 转换到 COFF 期间失败: 文件无效或损坏
2>
2>生成失败。
2>
2>已用时间 00:00:00.58
4>生成启动时间为 2016/9/19 10:40:22。
4>InitializeBuildStatus:
4>  正在对“flattests.dir\Debug\flattests.unsuccessfulbuild”执行 Touch 任务。
4>ClCompile:
4>  idl_gen_fbs.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
1>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_fbs.cpp
1>  idl_gen_text.cpp
4>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
4>  idl_gen_general.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
1>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_general.cpp
1>....\src\idl_gen_text.cpp(276): error C2556: “void flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”: 重载函数与“bool flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”只是在返回类型上不同
1>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
1>....\src\idl_gen_text.cpp(276): error C2371: “flatbuffers::GenerateText”: 重定义；不同的基类型
1>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
1>....\src\idl_gen_text.cpp(298): error C3861: “GenerateText”: 找不到标识符
1>  sample_text.cpp
4>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
4>....\src\idl_gen_general.cpp(1195): warning C4512: “flatbuffers::general::GeneralGenerator”: 未能生成赋值运算符
4>          ....\src\idl_gen_general.cpp(192) : 参见“flatbuffers::general::GeneralGenerator”的声明
4>  idl_parser.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
1>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
4>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>....\src\idl_gen_general.cpp(1195): warning C4512: “flatbuffers::general::GeneralGenerator”: 未能生成赋值运算符
3>          ....\src\idl_gen_general.cpp(192) : 参见“flatbuffers::general::GeneralGenerator”的声明
1>  Generating Code...
3>  idl_gen_go.cpp
1>
1>生成失败。
1>
1>已用时间 00:00:02.90
4>  idl_gen_text.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_js.cpp
4>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
4>....\src\idl_gen_text.cpp(276): error C2556: “void flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”: 重载函数与“bool flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”只是在返回类型上不同
4>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
4>....\src\idl_gen_text.cpp(276): error C2371: “flatbuffers::GenerateText”: 重定义；不同的基类型
4>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
4>....\src\idl_gen_text.cpp(298): error C3861: “GenerateText”: 找不到标识符
4>  test.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
4>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_php.cpp
4>  Generating Code...
4>
4>生成失败。
4>
4>已用时间 00:00:03.77
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_python.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_parser.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_cpp.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  idl_gen_text.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>....\src\idl_gen_text.cpp(276): error C2556: “void flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”: 重载函数与“bool flatbuffers::GenerateText(const flatbuffers::Parser &,const void *,std::string *)”只是在返回类型上不同
3>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
3>....\src\idl_gen_text.cpp(276): error C2371: “flatbuffers::GenerateText”: 重定义；不同的基类型
3>          C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(606) : 参见“flatbuffers::GenerateText”的声明
3>....\src\idl_gen_text.cpp(298): error C3861: “GenerateText”: 找不到标识符
3>  flatc.cpp
3>C:\Users\lx\Desktop\flatbuffers-for-actionscript-master\include\flatbuffers/idl.h(376): error C2614: “flatbuffers::IDLOptions”: 非法的成员初始化:“generate_object_based_api”不是基或成员
3>  Generating Code...
3>
3>生成失败。
3>
3>已用时间 00:00:08.00
========== 生成: 成功 0 个，失败 4 个，最新 0 个，跳过 0 个 ==========

**Comment by generalzgd** [comment]
/build_ide/VS2010/Release/ 在这个目录下有
